### ISSUE TITLE
[建议][写聚会的blog的时候可以把一些资料整理出来给大家？

### ISSUE THREAD

**Issue by lidashuang** [sdutlinux/sdutlinux.github.io#5]
类似teahour.fm 

![image](https://cloud.githubusercontent.com/assets/612381/7784743/4948c978-01a3-11e5-883b-c6a812ef4d2c.png)

@Junnplus @Ma233 

怎么样？

**Comment by Junnplus** [comment]
可以，我回去更新下blog
